### ISSUE TITLE
 System.NullReferenceException: Unable to get Form with ID: {guid} off disk or from the cache. 

### ISSUE THREAD

**Issue by BarryFogarty** [umbraco/Umbraco.Courier.FormsProvider#3]
When attempting to courier a form that is newly set up (i.e. does not yet exist on the target), it fails with the above error (stack trace below).  The file in question does exist on the local environment and permissions are set up correctly.  

NB The courier process works fine for forms that already exist on the target environment (updates are deployed).

Exception Message: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Unable to get Form with ID: '05647a87-a6ef-4a66-aa06-7df9b88ef5e3' off disk or from the cache. Check the file exists on disk at Umbraco.Forms.Data.Storage.FormStorage.GetForm(Guid id) at Umbraco.Courier.FormsProvider.FormItemProvider.HandlePack(ItemIdentifier id) in C:\a\1\s\Umbraco.Courier.FormsProvider\FormItemProvider.cs:line 162 at Umbraco.Courier.Core.ItemProvider.Package(ItemIdentifier id) at Umbraco.Courier.RepositoryProviders.Local.Package(ItemIdentifier itemId) at Umbraco.Courier.RepositoryProviders.Local.Hash(ItemIdentifier itemId) at Umbraco.Courier.RepositoryProviders.Webservices.Repository.GetItemHash(String sessionKey, ItemIdentifier itemId, String user, String pass) --- End of inner exception stack trace ---

Exception Type: System.Web.Services.Protocols.SoapException

Stack Trace:  at Umbraco.Courier.Core.TaskManager.GetSuccessfulProcessedTasks() at Umbraco.Courier.UI.Dialogs.CommitItem.GetTask(String id)

**Comment by BarryFogarty** [comment]
I worked around the issue by try - catching the code in the `FormItemProvider.HandlePack(ItemIdentifier id)` method, returning null after handling the exception.  

The cause of this problem is the method is also run **on the target** when called from the source.  As the file does not exist on the target yet, the inner `GetForm()` method throws the `FileNotFound` exception.

**Comment by warrenbuckley** [comment]
Thanks @BarryFogarty for this report.
Can I get some more details please.

What version of Umbraco, Forms & Courier are you using please?
I presume this was not a site on UaaS but a site that currently uses Courier for deployment?

Thanks,
Warren

**Comment by BarryFogarty** [comment]
Hey Warren,

Correct - not UaaS, it's Umbraco 7.4.3 on Azure.  Courier 2.52.13

**Comment by SteveVaneeckhout** [comment]
We are running on UaaS and are having the same problem. I'm trying to restore from production to local.

**Comment by jfsaliba** [comment]
I am experiencing the same problem as @BarryFogarty (I could Courier changes to existing identical-GUID forms successfully, but trying to transfer new form throws exception). Barry's try-catch suggestion did indeed work for me as well (replaced [L162](https://github.com/umbraco/Umbraco.Courier.FormsProvider/blob/master/Umbraco.Courier.FormsProvider/FormItemProvider.cs#L162) with the below code).

```c#
Forms.Core.Form form;
try
{
    form = fs.GetForm(Guid.Parse(id.Id));
}
catch (Exception ex)
{
    return null;
}
```

Perhaps ugly, but now I can Courier new forms from one instance to another. Thanks Barry!

(I'm using Umbraco 7.5.2, Courier 3.0.4, and Forms 4.3.2)

**Comment by cvocvo** [comment]
@warrenbuckley 
Also experiencing the same issue running: Umbraco 7.5.10, Courier 3.0.5, and Forms 4.4.2. @jfsaliba and @BarryFogarty's fix worked for me.

**Comment by warrenbuckley** [comment]
Apologies all, for forgetting about this. I will get this looked at this sprint.

**Comment by cvocvo** [comment]
@warrenbuckley Just ran into this issue, scratched my head and remembered I patched this DLL a while back. Has this been fixed in a new release?

**Comment by cvocvo** [comment]
@warrenbuckley Has this been fixed in a new release?

**Comment by warrenbuckley** [comment]
I have not had a chance to @cvocvo due to time constraints with other work items, but as you the community has found a fix for the problem, then I suggest you submit a PR to this project, that way the community gets credit for finding the fix.

**Comment by kamruzzamantitu** [comment]
I'm getting the same exception as @BarryFogarty even after adding try..catch block as per the suggestion from @jfsaliba for the new forms. Moreover when I'm trying to courier existing form, it shows 'No changes found' even though there are changes. Still if I courier it, the updates are not transferred.

I saw someone posted similar issue at https://our.umbraco.org/forum/umbraco-courier/86516-courier-not-transferring-forms-after-upgrade-to-umbraco-763-courier-311-forms-601. But no one replied.

FYI - I'm using Umbraco 7.6.1, Forms 6.0.1 and Courier 3.1.4.

**Comment by BarryFogarty** [comment]
PR:  https://github.com/umbraco/Umbraco.Courier.FormsProvider/pull/5

Better late than never ;-)

**Comment by SteveVaneeckhout** [comment]
But is this the correct fix? Should `fs.GetForm(Guid.Parse(id.Id));` throw an exception when the form doesn't exist?

**Comment by kamruzzamantitu** [comment]
@BarryFogarty thanks for the fix in PR but unfortunately it doesn't solve my problems (I already tried the try-catch block before posting my issue). Again my issues are:

1. When I'm trying to courier existing form, it shows 'No changes found' even though there are changes. Still if I courier it, the updates are not transferred.
2. Courier throws exception when I try to transfer new form Not sure where that exception comes from as my GetForm() code is already in a try..catch block.

Again, I'm using Umbraco 7.6.1, Forms 6.0.1 and Courier 3.1.4.

**Comment by warrenbuckley** [comment]
Hi @BarryFogarty 
First off apologies in our delay on getting back to you on this issue & your submitted PR.

I have managed to look at this yesterday and when applying your PR for this Courier & Forms deployment fix. I was still running into problems where it would not transfer the item.

So I am curious, was your fix intended for a certain combination of Umbraco, Courier & Forms?
Warren :)

**Comment by BarryFogarty** [comment]
Hey Warren, its been a while and I am no longer on the affected project, so I cannot verify the behaviour unfortunately.  Reading up the thread it was for Umbraco 7.4.3 on Azure. Courier 2.52.13.

I believe it transferred the item correctly when the code in the PR was added, as it was the code running on the target that was generating the exception.  When run on the source, the form file would be found by GUID and it would transfer as a new item.  I can't be 100% but in my mind this change did indeed fix the problem.

**Comment by warrenbuckley** [comment]
Hi @BarryFogarty OK I will have to do some more testing & investigation tomorrow to see I can get this resolved.

Appreciate the feedback.
Warren :)

**Comment by SimonAntony** [comment]
Hi @warrenbuckley - how are you getting on with this? We've just taken over a site with this issue, common thing here seems to be Azure - i've not seen this happen before apart from when we had that Dropbox issue we discussed a few months back.
