### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Vassi** [umbraco/Umbraco.Courier.FormsProvider#4]
The Courier.Core package doesn't seem to be available anymore and causes the build process to fail whether I open the solution and try it myself or use your build.bat.

NuGet Package restore failed for project Umbraco.Courier.FormsTreeProvider: Unable to find version '2.51.3' of package 'Courier.Core'.

**Comment by Vassi** [comment]
I should add, with some futzing around, updating the package versions did the trick, but just changing the packages.config wasn't enough as the project references were still actively looking in the wrong place. A more thorough cleanup is necessary.

**Comment by nul800sebastiaan** [comment]
Just going through some old issues, cloning and then building seems to work now, so I'll close this one.
